name: Kwiki-Raw
version: 0.02
abstract: Action to retrieve the wiki text of a page
author: Chris Dent <cdent@burningchrome.com>
license: perl
distribution_type: module
requires:
  Kwiki: 0.37
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
